version: '3.8'
services:
  webservice: # 服務名稱
    image: casper723/ironman-app-2023-mongo-amd64:latest
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo/docker-sample-products?authSource=admin
      - VARIABLE=${VARIABLE}
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    depends_on:
      - mongo
    restart: on-failure
    networks: # 此網路設定需要與 traefik 一致
      - casper
    labels:
      - traefik.enable=true
      - "traefik.http.routers.webservice.entrypoints=web" # 使用 web 入口點，對應到 80 端口
      - "traefik.http.routers.webservice.rule=Host(`ironman-node.casper.tw`)" # 對應到 custom2.xxx 主機名
      - "traefik.http.routers.webservice.service=web" # 設置服務為 Traefik 的內部 API
      - traefik.http.services.webservice.loadbalancer.server.port=3000

  mongo: # 服務名稱
    image: mongo:latest # dokcer hub
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=docker-sample-products
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks: # 此網路設定需要與 traefik 一致
      - casper


volumes:
  mongo-data:

networks: # 最後，也再加入網路設定，所有需要使用相同 traefik 群組的，都要加入
  casper:
      name: casper-network